kite:
  host: "https://weyma-kite.infra.dubyatp.xyz"
  deploymentStrategy:
    type: Recreate
  secret:
    create: false
    existingSecret: kite-secret
  db:
    sqlite:
      persistence:
        pvc:
          enabled: true
  ingress:
    enabled: true
    className: "traefik"
    hosts:
      - host: weyma-kite.infra.dubyatp.xyz
        paths:
          - path: /
            pathType: ImplementationSpecific
  podAnnotations:
    backup.velero.io/backup-volumes: kite-storage