kite:
  host: "https://weyma-kite.infra.dubyatp.xyz"
  ingress:
    enabled: true
    className: "traefik"
    hosts:
      - host: weyma-kite.infra.dubyatp.xyz
        paths:
          - path: /
            pathType: ImplementationSpecific